version: '3.8'

services:
  frontend-customer-site:
    build:
      context: ./frontend/customer-site
    ports:
      - "8080:80"
    # Add your domain configuration for customer site

  frontend-admin-site:
    build:
      context: ./frontend/admin-site
    ports:
      - "8081:80"
    # Add your domain configuration for admin site

  frontend-delivery-site:
    build:
      context: ./frontend/delivery-site
    ports:
      - "8082:80"
    # Add your domain configuration for delivery site

  backend-api:
    build: ./backend/api
    ports:
      - "3000:3000"
    depends_on:
      - backend-db
    # Add your backend configuration

  backend-db:
    build: ./backend/db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "restaurant_management_system"
    ports:
      - "3306:3306"
    # Add your database configuration

  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Add your nginx configuration
